/////////////////////////////////////////////////////////////////////////////
// Name:        balancewindow.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     12/12/2013 19:40:05
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 12/12/2013 19:40:05

#ifndef _BALANCEWINDOW_H_
#define _BALANCEWINDOW_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CBALANCEWINDOW 10009
#define ID_TEXTCTRL2 10005
#define ID_CHOICE 10022
#define ID_TEXTCTRL7 10023
#define ID_BUTTON7 10024
#define ID_TEXTCTRL3 10006
#define ID_BUTTON1 10007
#define ID_BUTTON2 10008
#define SYMBOL_CBALANCEWINDOW_STYLE wxCAPTION|wxRESIZE_BORDER|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CBALANCEWINDOW_TITLE _("Ω·À„")
#define SYMBOL_CBALANCEWINDOW_IDNAME ID_CBALANCEWINDOW
#define SYMBOL_CBALANCEWINDOW_SIZE wxSize(400, 300)
#define SYMBOL_CBALANCEWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CBalanceWindow class declaration
 */

class CBalanceWindow: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CBalanceWindow )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CBalanceWindow();
    CBalanceWindow( wxWindow* parent, wxWindowID id = SYMBOL_CBALANCEWINDOW_IDNAME, const wxString& caption = SYMBOL_CBALANCEWINDOW_TITLE, const wxPoint& pos = SYMBOL_CBALANCEWINDOW_POSITION, const wxSize& size = SYMBOL_CBALANCEWINDOW_SIZE, long style = SYMBOL_CBALANCEWINDOW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CBALANCEWINDOW_IDNAME, const wxString& caption = SYMBOL_CBALANCEWINDOW_TITLE, const wxPoint& pos = SYMBOL_CBALANCEWINDOW_POSITION, const wxSize& size = SYMBOL_CBALANCEWINDOW_SIZE, long style = SYMBOL_CBALANCEWINDOW_STYLE );

    /// Destructor
    ~CBalanceWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CBalanceWindow event handler declarations
    /// wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE
    void OnCustomerTypeSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON7
    void OnMemberVerifyBtnClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON1
    void OnSubmitBtnClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON2
    void OnCancelBtnClick( wxCommandEvent& event );

    void OnProcessMemberDataTextEnter(wxCommandEvent& event);

////@end CBalanceWindow event handler declarations

////@begin CBalanceWindow member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CBalanceWindow member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();


private:

////@begin CBalanceWindow member variables
    wxTextCtrl* m_pConsumeAmountText;
    wxChoice* m_pCustomerTypeChoices;
    wxTextCtrl* m_pCustomerDataText;
    wxButton* m_pMemeberVerifyBtn;
    wxTextCtrl* m_pConsumeDetailText;
    wxBoxSizer* m_pMemberVerifySizer;
    wxBoxSizer* m_pCustomerInfoSizer;
    wxStaticText* m_pCustomerInfoLabel;
    wxButton* m_pSubmitBtn;
////@end CBalanceWindow member variables
};

#endif
    // _BALANCEWINDOW_H_
