/////////////////////////////////////////////////////////////////////////////
// Name:        accountwindow.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     13/12/2013 13:59:10
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 13/12/2013 13:59:10

#ifndef _ACCOUNTWINDOW_H_
#define _ACCOUNTWINDOW_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxListCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CACCOUNTWINDOW 10022
#define ID_LISTCTRL 10023
#define SYMBOL_CACCOUNTWINDOW_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CACCOUNTWINDOW_TITLE _("’Àªßπ‹¿Ì")
#define SYMBOL_CACCOUNTWINDOW_IDNAME ID_CACCOUNTWINDOW
#define SYMBOL_CACCOUNTWINDOW_SIZE wxSize(600, 300)
#define SYMBOL_CACCOUNTWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CAccountWindow class declaration
 */

class CAccountWindow: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CAccountWindow )

public:
    /// Constructors
    CAccountWindow();
    CAccountWindow( wxWindow* parent, wxWindowID id = SYMBOL_CACCOUNTWINDOW_IDNAME, const wxString& caption = SYMBOL_CACCOUNTWINDOW_TITLE, const wxPoint& pos = SYMBOL_CACCOUNTWINDOW_POSITION, const wxSize& size = SYMBOL_CACCOUNTWINDOW_SIZE, long style = SYMBOL_CACCOUNTWINDOW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CACCOUNTWINDOW_IDNAME, const wxString& caption = SYMBOL_CACCOUNTWINDOW_TITLE, const wxPoint& pos = SYMBOL_CACCOUNTWINDOW_POSITION, const wxSize& size = SYMBOL_CACCOUNTWINDOW_SIZE, long style = SYMBOL_CACCOUNTWINDOW_STYLE );

    /// Destructor
    ~CAccountWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CAccountWindow event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON7
    void OnAccountModifyBtnClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON8
    void OnAccountAddBtnClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON9
    void OnAccountDeleteBtnClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON10
    void OnAccountCloseBtnClick( wxCommandEvent& event );
////@end CAccountWindow event handler declarations

////@begin CAccountWindow member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CAccountWindow member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    void UpdateData();

////@begin CAccountWindow member variables
    wxListCtrl* m_pAccountList;
    wxButton* m_pAccountModifyBtn;
    wxButton* m_pAccountRegisterBtn;
    wxButton* m_pAccountCloseBtn;
////@end CAccountWindow member variables
};

#endif
    // _ACCOUNTWINDOW_H_
