/////////////////////////////////////////////////////////////////////////////
// Name:        cloginwindow.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     12/12/2013 13:40:26
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 12/12/2013 13:40:26

#ifndef _CLOGINWINDOW_H_
#define _CLOGINWINDOW_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CLOGINWINDOW 10000
#define ID_TEXTCTRL 10001
#define ID_TEXTCTRL1 10002
#define ID_BUTTON 10003
#define SYMBOL_CLOGINWINDOW_STYLE wxCAPTION|wxSYSTEM_MENU|wxCLOSE_BOX|wxSTAY_ON_TOP
#define SYMBOL_CLOGINWINDOW_TITLE _("µÇÂ½")
#define SYMBOL_CLOGINWINDOW_IDNAME ID_CLOGINWINDOW
#define SYMBOL_CLOGINWINDOW_SIZE wxSize(400, 300)
#define SYMBOL_CLOGINWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CLoginWindow class declaration
 */

class CLoginWindow: public wxDialog
{    
    DECLARE_CLASS( CLoginWindow )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CLoginWindow();
    CLoginWindow( wxWindow* parent, wxWindowID id = SYMBOL_CLOGINWINDOW_IDNAME, const wxString& caption = SYMBOL_CLOGINWINDOW_TITLE, const wxPoint& pos = SYMBOL_CLOGINWINDOW_POSITION, const wxSize& size = SYMBOL_CLOGINWINDOW_SIZE, long style = SYMBOL_CLOGINWINDOW_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CLOGINWINDOW_IDNAME, const wxString& caption = SYMBOL_CLOGINWINDOW_TITLE, const wxPoint& pos = SYMBOL_CLOGINWINDOW_POSITION, const wxSize& size = SYMBOL_CLOGINWINDOW_SIZE, long style = SYMBOL_CLOGINWINDOW_STYLE );

    /// Destructor
    ~CLoginWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

    ////@begin CLoginWindow event handler declarations
    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_TEXTCTRL
    void OnLoginAccountTextEnter( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_TEXTCTRL1
    void OnLoginPasswordTextEnter( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
    void OnLoginBtnClick( wxCommandEvent& event );
    void OnPaint( wxPaintEvent& event );

    ////@end CLoginWindow event handler declarations


////@begin CLoginWindow member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CLoginWindow member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin CLoginWindow member variables
    wxTextCtrl* m_pLoginAccountText;
    wxTextCtrl* m_pLoginPasswordText;
    wxButton* m_pLoginBtn;
    wxImage* m_pBackGroundImage;
    wxPanel* m_pMainPanel;
////@end CLoginWindow member variables
};

#endif
    // _CLOGINWINDOW_H_
