/////////////////////////////////////////////////////////////////////////////
// Name:        memberregisterwindow.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/12/2013 01:30:14
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/12/2013 01:30:14

#ifndef _MEMBERREGISTERWINDOW_H_
#define _MEMBERREGISTERWINDOW_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/datectrl.h"
#include "wx/dateevt.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxDatePickerCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CMEMBERREGISTERWINDOW 10029
#define ID_TEXTCTRL9 10030
#define ID_TEXTCTRL10 10031
#define ID_TEXTCTRL11 10032
#define ID_DATEPICKERCTRL 10033
#define ID_CHOICE1 10034
#define ID_BUTTON10 10035
#define SYMBOL_CMEMBERREGISTERWINDOW_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CMEMBERREGISTERWINDOW_TITLE _("»áÔ±×¢²á")
#define SYMBOL_CMEMBERREGISTERWINDOW_IDNAME ID_CMEMBERREGISTERWINDOW
#define SYMBOL_CMEMBERREGISTERWINDOW_SIZE wxSize(400, 400)
#define SYMBOL_CMEMBERREGISTERWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CMemberRegisterWindow class declaration
 */

class CMemberRegisterWindow: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CMemberRegisterWindow )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CMemberRegisterWindow();
    CMemberRegisterWindow( wxWindow* parent, wxWindowID id = SYMBOL_CMEMBERREGISTERWINDOW_IDNAME, const wxString& caption = SYMBOL_CMEMBERREGISTERWINDOW_TITLE, const wxPoint& pos = SYMBOL_CMEMBERREGISTERWINDOW_POSITION, const wxSize& size = SYMBOL_CMEMBERREGISTERWINDOW_SIZE, long style = SYMBOL_CMEMBERREGISTERWINDOW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CMEMBERREGISTERWINDOW_IDNAME, const wxString& caption = SYMBOL_CMEMBERREGISTERWINDOW_TITLE, const wxPoint& pos = SYMBOL_CMEMBERREGISTERWINDOW_POSITION, const wxSize& size = SYMBOL_CMEMBERREGISTERWINDOW_SIZE, long style = SYMBOL_CMEMBERREGISTERWINDOW_STYLE );

    /// Destructor
    ~CMemberRegisterWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CMemberRegisterWindow event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON10
    void OnMemberRegisterBtnClick( wxCommandEvent& event );

////@end CMemberRegisterWindow event handler declarations

////@begin CMemberRegisterWindow member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CMemberRegisterWindow member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin CMemberRegisterWindow member variables
    wxTextCtrl* m_pNameText;
    wxTextCtrl* m_pTelText;
    wxTextCtrl* m_pBalanceText;
    wxDatePickerCtrl* m_pBirthdayDatePicker;
    wxChoice* m_pDiscountTypeChoice;
    wxButton* m_pRegisterBtn;
////@end CMemberRegisterWindow member variables
};

#endif
    // _MEMBERREGISTERWINDOW_H_
