/////////////////////////////////////////////////////////////////////////////
// Name:        memberviewwindow.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/12/2013 16:55:30
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/12/2013 16:55:30

#ifndef _MEMBERVIEWWINDOW_H_
#define _MEMBERVIEWWINDOW_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/listctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxListCtrl;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CMEMBERVIEWWINDOW 10036
#define ID_LISTCTRL 10037
#define ID_BUTTON11 10038
#define ID_BUTTON12 10039
#define SYMBOL_CMEMBERVIEWWINDOW_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CMEMBERVIEWWINDOW_TITLE _("会员信息")
#define SYMBOL_CMEMBERVIEWWINDOW_IDNAME ID_CMEMBERVIEWWINDOW
#define SYMBOL_CMEMBERVIEWWINDOW_SIZE wxSize(600, 300)
#define SYMBOL_CMEMBERVIEWWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CMemberViewWindow class declaration
 */

class CMemberViewWindow: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CMemberViewWindow )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CMemberViewWindow();
    CMemberViewWindow( wxWindow* parent, wxWindowID id = SYMBOL_CMEMBERVIEWWINDOW_IDNAME, const wxString& caption = SYMBOL_CMEMBERVIEWWINDOW_TITLE, const wxPoint& pos = SYMBOL_CMEMBERVIEWWINDOW_POSITION, const wxSize& size = SYMBOL_CMEMBERVIEWWINDOW_SIZE, long style = SYMBOL_CMEMBERVIEWWINDOW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CMEMBERVIEWWINDOW_IDNAME, const wxString& caption = SYMBOL_CMEMBERVIEWWINDOW_TITLE, const wxPoint& pos = SYMBOL_CMEMBERVIEWWINDOW_POSITION, const wxSize& size = SYMBOL_CMEMBERVIEWWINDOW_SIZE, long style = SYMBOL_CMEMBERVIEWWINDOW_STYLE );

    /// Destructor
    ~CMemberViewWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CMemberViewWindow event handler declarations
    void OnListctrlItemActivated( wxListEvent& event );
    void OnListctrlColClick( wxListEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON11
    void OnViewHistoryBtnClick( wxCommandEvent& event );
    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON12
    void OnCloseClick( wxCommandEvent& event );

////@end CMemberViewWindow event handler declarations

////@begin CMemberViewWindow member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CMemberViewWindow member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    void UpdateData();
    static int wxCALLBACK MemberRegisterDateCompare(wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData);
    static int wxCALLBACK MemberBirthDayCompare(wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData);
    static int wxCALLBACK MemberBalanceCompare(wxIntPtr item1, wxIntPtr item2, wxIntPtr sortData);

private:
////@begin CMemberViewWindow member variables
    bool m_bSortReverse;
    wxStaticText* m_pMemberCountLabel;
    wxStaticText* m_pAllMoneyLabel;
    wxListCtrl* m_pMemberInfoList;
    wxButton*  m_pViewHistoryBtn;
    wxButton* m_pCloseBtn;
////@end CMemberViewWindow member variables
};

#endif