/////////////////////////////////////////////////////////////////////////////
// Name:        memberwindow.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     14/12/2013 00:18:04
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 14/12/2013 00:18:04

#ifndef _MEMBERWINDOW_H_
#define _MEMBERWINDOW_H_


/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CMEMBERWINDOW 10025
#define ID_TEXTCTRL8 10026
#define ID_BUTTON8 10027
#define ID_BUTTON9 10028
#define ID_BUTTON 10000
#define SYMBOL_CMEMBERWINDOW_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CMEMBERWINDOW_TITLE _("»áÔ±µÇÂ½")
#define SYMBOL_CMEMBERWINDOW_IDNAME ID_CMEMBERWINDOW
#define SYMBOL_CMEMBERWINDOW_SIZE wxSize(400, 300)
#define SYMBOL_CMEMBERWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CMemberWindow class declaration
 */

class CMemberWindow: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CMemberWindow )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CMemberWindow();
    CMemberWindow( wxWindow* parent, wxWindowID id = SYMBOL_CMEMBERWINDOW_IDNAME, const wxString& caption = SYMBOL_CMEMBERWINDOW_TITLE, const wxPoint& pos = SYMBOL_CMEMBERWINDOW_POSITION, const wxSize& size = SYMBOL_CMEMBERWINDOW_SIZE, long style = SYMBOL_CMEMBERWINDOW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CMEMBERWINDOW_IDNAME, const wxString& caption = SYMBOL_CMEMBERWINDOW_TITLE, const wxPoint& pos = SYMBOL_CMEMBERWINDOW_POSITION, const wxSize& size = SYMBOL_CMEMBERWINDOW_SIZE, long style = SYMBOL_CMEMBERWINDOW_STYLE );

    /// Destructor
    ~CMemberWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CMemberWindow event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON8
    void OnMemberBtnClick( wxCommandEvent& event );

    void OnMemberRegisterBtnClick(wxCommandEvent& event);

    void OnViewAllMemberClick( wxCommandEvent& event );

////@end CMemberWindow event handler declarations

////@begin CMemberWindow member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CMemberWindow member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin CMemberWindow member variables
    wxTextCtrl* m_pMemberTelText;
////@end CMemberWindow member variables
};

#endif
    // _MEMBERWINDOW_H_
