/////////////////////////////////////////////////////////////////////////////
// Name:        summarywindow.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     12/12/2013 21:58:25
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 12/12/2013 21:58:25

#ifndef _SUMMARYWINDOW_H_
#define _SUMMARYWINDOW_H_


/*!
* Includes
*/

////@begin includes
#include "wx/datectrl.h"
#include "wx/dateevt.h"
#include "wx/grid.h"
////@end includes

/*!
* Forward declarations
*/

////@begin forward declarations
class wxDatePickerCtrl;
class wxGrid;
////@end forward declarations

/*!
* Control identifiers
*/

////@begin control identifiers
#define ID_CSUMMARYWINDOW 10004
#define ID_DATECTRL 10013
#define ID_COMBOBOX 10014
#define ID_GRID 10010
#define ID_BUTTON3 10011
#define ID_BUTTON4 10012
#define SYMBOL_CSUMMARYWINDOW_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_CSUMMARYWINDOW_TITLE _("–≈œ¢“ª¿¿")
#define SYMBOL_CSUMMARYWINDOW_IDNAME ID_CSUMMARYWINDOW
#define SYMBOL_CSUMMARYWINDOW_SIZE wxSize(800, 600)
#define SYMBOL_CSUMMARYWINDOW_POSITION wxDefaultPosition
////@end control identifiers


/*!
* CSummaryWindow class declaration
*/

#include "../ConsumeRecord/ConsumeRecord.h"


class CSummaryWindow: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CSummaryWindow )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CSummaryWindow();
    CSummaryWindow( wxWindow* parent, wxWindowID id = SYMBOL_CSUMMARYWINDOW_IDNAME, const wxString& caption = SYMBOL_CSUMMARYWINDOW_TITLE, const wxPoint& pos = SYMBOL_CSUMMARYWINDOW_POSITION, const wxSize& size = SYMBOL_CSUMMARYWINDOW_SIZE, long style = SYMBOL_CSUMMARYWINDOW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CSUMMARYWINDOW_IDNAME, const wxString& caption = SYMBOL_CSUMMARYWINDOW_TITLE, const wxPoint& pos = SYMBOL_CSUMMARYWINDOW_POSITION, const wxSize& size = SYMBOL_CSUMMARYWINDOW_SIZE, long style = SYMBOL_CSUMMARYWINDOW_STYLE );

    /// Destructor
    ~CSummaryWindow();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

    ////@begin CSummaryWindow event handler declarations

    /// wxEVT_DATE_CHANGED event handler for ID_DATECTRL
    void OnSummaryDateChanged( wxDateEvent& event );

    /// wxEVT_COMMAND_COMBOBOX_SELECTED event handler for ID_COMBOBOX
    void OnSummaryViewTypeSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3
    void OnSummaryBtnClick( wxCommandEvent& event );
    void OnCloseBtnClick( wxCommandEvent& event );

    ////@end CSummaryWindow event handler declarations

    ////@begin CSummaryWindow member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
    ////@end CSummaryWindow member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    void UpdateByDate();

    void ShowRecord(const CConsumeRecord* pRecord, size_t uRowIndex);

private:
    ////@begin CSummaryWindow member variables
    wxDatePickerCtrl* m_pSummaryDatePicker;
    wxComboBox* m_pSummaryViewTypeCombo;
    wxGrid* m_pSummaryGrid;
    wxStaticText* m_pSummaryLabel;
    wxButton* m_pSummaryBtn;
    wxButton* m_pSummaryCloseBtn;
};

#endif
// _SUMMARYWINDOW_H_
